vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        avatar:
            uri_prefix: /uploads/avatar
            upload_destination: '%kernel.project_dir%/public/uploads/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        post:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer